// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServNameClient is the client API for MyServName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServNameClient interface {
	Say(ctx context.Context, in *People, opts ...grpc.CallOption) (*Student, error)
}

type myServNameClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServNameClient(cc grpc.ClientConnInterface) MyServNameClient {
	return &myServNameClient{cc}
}

func (c *myServNameClient) Say(ctx context.Context, in *People, opts ...grpc.CallOption) (*Student, error) {
	out := new(Student)
	err := c.cc.Invoke(ctx, "/pb.MyServName/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServNameServer is the server API for MyServName service.
// All implementations must embed UnimplementedMyServNameServer
// for forward compatibility
type MyServNameServer interface {
	Say(context.Context, *People) (*Student, error)
	mustEmbedUnimplementedMyServNameServer()
}

// UnimplementedMyServNameServer must be embedded to have forward compatible implementations.
type UnimplementedMyServNameServer struct {
}

func (UnimplementedMyServNameServer) Say(context.Context, *People) (*Student, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}
func (UnimplementedMyServNameServer) mustEmbedUnimplementedMyServNameServer() {}

// UnsafeMyServNameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServNameServer will
// result in compilation errors.
type UnsafeMyServNameServer interface {
	mustEmbedUnimplementedMyServNameServer()
}

func RegisterMyServNameServer(s grpc.ServiceRegistrar, srv MyServNameServer) {
	s.RegisterService(&MyServName_ServiceDesc, srv)
}

func _MyServName_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(People)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServNameServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyServName/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServNameServer).Say(ctx, req.(*People))
	}
	return interceptor(ctx, in, info, handler)
}

// MyServName_ServiceDesc is the grpc.ServiceDesc for MyServName service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyServName_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MyServName",
	HandlerType: (*MyServNameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _MyServName_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myproto.proto",
}
